name: build

on: [push, pull_request]
jobs:
  wollok-ts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          npm i -g wollok-ts-cli
        shell: bash
        name: Setup Wollok CLI
      - run: npx wollok-ts-cli test --skipValidations -p ./
        name: Run tests
